service: TruePackage

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  envionment: production
  stage: production

functions:
  api:
    handler: handler.handler
    events:
     - http:
         path: "{proxy+}"
         method: any
         cors:
          origins: 
            - '*'
          request:
            template:
              application/json: '{ "httpMethod" : "$context.httpMethod" }'
  playground:
    handler: handler.playground
    events: 
      - http:
          path: "/playground"
          method: "get"
          cors: true  
package:
  individually: true

plugins:
  - serverless-offline
  # - serverless-offline-scheduler
  - serverless-webpack

custom:
  serverless-offline:
    babelOptions: 
      presets: ["es2015", "stage-3"]
  stage: "production"
  webpack: ./webpack.config.js
  webpackIncludeModules:
    packagePath: './package.json'
